# Documentation Deployment with GitHub Actions

name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Setup Python
        run: uv sync --group docs
      - name: Build docs
        run: uv run mkdocs build --clean
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: site/
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
