# Documentation Deployment with GitHub Actions

name: Deploy Documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --group docs

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages --depth=1 || echo "gh-pages branch does not exist yet"

      - name: Deploy documentation
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            # Deploy tagged version
            VERSION=${GITHUB_REF#refs/tags/v}
            uv run mike deploy $VERSION latest --update-aliases --push
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            # Deploy development version
            uv run mike deploy dev --push
          fi

      - name: Set default version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          uv run mike set-default latest --push
